import { calculateKoreanCryptoTaxes } from "./tax_calculation_engine.js";
import { buildTaxSummary } from "../reports/tax_summary_report.js";

export const REALISTIC_REGRESSION_SAMPLE = [
  {
    id: "btc-buy-sample",
    timestamp: "2024-01-01T00:00:00.000Z",
    event_type: "TRADE_BUY",
    income_category: "CAPITAL_GAIN",
    asset_in: "BTC",
    amount_in: 1,
    asset_out: "USDT",
    amount_out: 38000,
    price_usdt: 38000,
    price_krw: 49400000,
    amount_in_krw: 49400000,
    amount_out_krw: 49400000,
    pricing_source: "TRADE_EXECUTION_PRICE",
    source_name: "Binance",
    exchange: "Binance",
  },
  {
    id: "eth-buy-sample",
    timestamp: "2024-01-02T00:00:00.000Z",
    event_type: "TRADE_BUY",
    income_category: "CAPITAL_GAIN",
    asset_in: "ETH",
    amount_in: 1,
    asset_out: "USDT",
    amount_out: 2200,
    price_usdt: 2200,
    price_krw: 2860000,
    amount_in_krw: 2860000,
    amount_out_krw: 2860000,
    pricing_source: "TRADE_EXECUTION_PRICE",
    source_name: "Binance",
    exchange: "Binance",
  },
  {
    id: "arb-airdrop-sample",
    timestamp: "2024-01-03T00:00:00.000Z",
    event_type: "AIRDROP",
    income_category: "AIRDROP_INCOME",
    asset_in: "ARB",
    amount_in: 100,
    amount_out: null,
    price_usdt: 2,
    price_krw: 2600,
    amount_in_krw: 260000,
    amount_out_krw: null,
    pricing_source: "BINANCE_KLINES_1H_NEAREST",
    source_name: "Binance Distribution History",
    exchange: "Binance",
  },
  {
    id: "eth-staking-sample",
    timestamp: "2024-01-04T00:00:00.000Z",
    event_type: "STAKING_REWARD",
    income_category: "STAKING_INCOME",
    asset_in: "ETH",
    amount_in: 0.1,
    amount_out: null,
    price_usdt: 2400,
    price_krw: 3120000,
    amount_in_krw: 312000,
    amount_out_krw: null,
    pricing_source: "BINANCE_KLINES_1H_NEAREST",
    source_name: "Binance Earn/Staking History",
    exchange: "Binance",
  },
  {
    id: "btc-sell-sample",
    timestamp: "2024-02-01T00:00:00.000Z",
    event_type: "TRADE_SELL",
    income_category: "CAPITAL_GAIN",
    asset_in: "USDT",
    amount_in: 42000,
    asset_out: "BTC",
    amount_out: 1,
    price_usdt: 42000,
    price_krw: 54600000,
    amount_in_krw: 54600000,
    amount_out_krw: 54600000,
    pricing_source: "TRADE_EXECUTION_PRICE",
    source_name: "Binance",
    exchange: "Binance",
  },
  {
    id: "eth-sell-sample",
    timestamp: "2024-02-02T00:00:00.000Z",
    event_type: "TRADE_SELL",
    income_category: "CAPITAL_GAIN",
    asset_in: "USDT",
    amount_in: 2600,
    asset_out: "ETH",
    amount_out: 1,
    price_usdt: 2600,
    price_krw: 3380000,
    amount_in_krw: 3380000,
    amount_out_krw: 3380000,
    pricing_source: "TRADE_EXECUTION_PRICE",
    source_name: "Binance",
    exchange: "Binance",
  },
];

export function runRealisticRegressionSample() {
  const result = calculateKoreanCryptoTaxes(REALISTIC_REGRESSION_SAMPLE, "demo-user");
  const summary = buildTaxSummary(result.unifiedTransactions, result.realizedLots, result.warnings);

  return {
    result,
    summary,
    checks: {
      capital_gain_positive: result.taxSummary.capital_gain_krw > 0,
      total_taxable_positive: result.taxSummary.total_taxable_income_krw > 0,
      airdrop_income_positive: result.taxSummary.airdrop_income_krw > 0,
      staking_income_positive: result.taxSummary.staking_income_krw > 0,
    },
  };
}
