export const EVM_PROVIDER_ID = "demo-evm-provider";

export async function fetchEvmWalletActivity({ walletAddress, chain }) {
  const wallet = String(walletAddress || "").toLowerCase();
  const nativeAsset = getNativeAsset(chain);

  return [
    {
      kind: "NATIVE_TRANSFER",
      direction: "IN",
      txHash: `${chain}-0xin-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-01T00:15:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: `0xfeed${wallet.slice(2, 38)}`,
      toAddress: wallet,
      assetSymbol: nativeAsset,
      amount: 1.25,
      fee: 0.00042,
      feeAsset: nativeAsset,
      summary: `${nativeAsset} incoming transfer to registered wallet`,
      provider: EVM_PROVIDER_ID,
      protocol: "",
    },
    {
      kind: "TOKEN_TRANSFER",
      direction: "OUT",
      txHash: `${chain}-0xout-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-02T09:00:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: wallet,
      toAddress: `0xbinance${wallet.slice(2, 34)}`,
      assetSymbol: "USDC",
      tokenAddress: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
      amount: 250,
      fee: 0.00051,
      feeAsset: nativeAsset,
      summary: "USDC outgoing transfer to external deposit address",
      provider: EVM_PROVIDER_ID,
      protocol: "",
    },
    {
      kind: "SWAP",
      direction: "OUT",
      txHash: `${chain}-0xswap-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-03T13:40:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: wallet,
      toAddress: "0xdef1c0ded9bec7f1a1670819833240f027b25eff",
      assetSentSymbol: "USDC",
      amountSent: 300,
      assetReceivedSymbol: nativeAsset,
      amountReceived: 0.11,
      fee: 0.00073,
      feeAsset: nativeAsset,
      summary: `Swap-like transaction on ${chain}`,
      provider: EVM_PROVIDER_ID,
      protocol: "DEX_ROUTER_PLACEHOLDER",
    },
    {
      kind: "APPROVAL",
      direction: "OUT",
      txHash: `${chain}-0xappr-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-03T13:35:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: wallet,
      toAddress: "0xdef1c0ded9bec7f1a1670819833240f027b25eff",
      assetSymbol: "USDC",
      amount: 0,
      fee: 0.00021,
      feeAsset: nativeAsset,
      summary: "ERC-20 approval preserved for audit trail",
      provider: EVM_PROVIDER_ID,
      protocol: "DEX_ROUTER_PLACEHOLDER",
    },
    {
      kind: "UNKNOWN",
      direction: "OUT",
      txHash: `${chain}-0xunk-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-04T07:20:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: wallet,
      toAddress: "0xcomplexprotocol00000000000000000000000000",
      fee: 0.00091,
      feeAsset: nativeAsset,
      summary: "Complex multi-leg contract interaction retained as UNKNOWN",
      provider: EVM_PROVIDER_ID,
      protocol: "COMPLEX_PROTOCOL_PLACEHOLDER",
      rawLegs: [
        { token: "USDC", amount: 15, direction: "OUT" },
        { token: "LP-XYZ", amount: 1.2, direction: "IN" },
      ],
    },
    {
      kind: "AIRDROP",
      direction: "IN",
      txHash: `${chain}-0xair-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-05T08:00:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: "0xairdropdistribution0000000000000000000000",
      toAddress: wallet,
      assetSymbol: "ARB",
      amount: 75,
      fee: 0.00019,
      feeAsset: nativeAsset,
      summary: "Token airdrop distribution claim",
      provider: EVM_PROVIDER_ID,
      protocol: "AIRDROP_DISTRIBUTOR",
    },
    {
      kind: "STAKING_REWARD",
      direction: "IN",
      txHash: `${chain}-0xstk-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-06T06:30:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: "0xlidostakingrewards0000000000000000000000",
      toAddress: wallet,
      assetSymbol: nativeAsset,
      amount: 0.023,
      fee: 0.00015,
      feeAsset: nativeAsset,
      summary: "Staking reward distribution",
      provider: EVM_PROVIDER_ID,
      protocol: "LIDO_STAKING",
    },
    {
      kind: "UNKNOWN",
      direction: "OUT",
      txHash: `${chain}-0xlpadd-${wallet.slice(2, 10)}`,
      timestamp: "2026-03-06T09:45:00.000Z",
      chain,
      walletAddress: wallet,
      fromAddress: wallet,
      toAddress: "0xcurvepool00000000000000000000000000000000",
      assetSentSymbol: "USDC",
      amountSent: 120,
      assetReceivedSymbol: "LP-CRV",
      amountReceived: 10,
      fee: 0.00064,
      feeAsset: nativeAsset,
      summary: "Liquidity add transaction",
      provider: EVM_PROVIDER_ID,
      protocol: "CURVE_POOL",
      rawLegs: [
        { token: "USDC", amount: 120, direction: "OUT" },
        { token: nativeAsset, amount: 0.08, direction: "OUT" },
        { token: "LP-CRV", amount: 10, direction: "IN" },
      ],
    },
  ];
}

function getNativeAsset(chain) {
  const nativeByChain = {
    ethereum: "ETH",
    arbitrum: "ETH",
    optimism: "ETH",
    base: "ETH",
    polygon: "MATIC",
    bsc: "BNB",
    avalanche: "AVAX",
  };
  return nativeByChain[chain] || "ETH";
}
